---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

env:
  global:
    - JOBS=1

install:
  - yarn install --pure-lockfile

script:
  - for dir in ./examples/* ; do (cd "$dir"; yarn run lint:hbs; yarn run lint:js; yarn test); done
  - cd bootstrap
  - yarn run lint:hbs
  - yarn run lint:js
  - yarn test

notifications:
  email: false
